#!/usr/bin/env python3
"""Emit values/values-fr/values-de strings.xml from one catalog."""
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1] / "app/src/main/res"

# key -> (en, fr, de)
CATALOG = {
    "app_name": ("Paperorg Notes", "Paperorg Notes", "Paperorg Notes"),
    "brand_tagline": ("Capture, transcribe, send", "Enregistrer, transcrire, envoyer", "Aufnehmen, transkribieren, senden"),
    "tab_record": ("Record", "Enregistrer", "Aufnahme"),
    "tab_notes": ("Notes", "Notes", "Notizen"),
    "tab_search": ("Search", "Recherche", "Suche"),
    "tab_settings": ("Settings", "Réglages", "Einstellungen"),
    "privacy_title": ("Your recordings stay yours", "Vos enregistrements restent les vôtres", "Ihre Aufnahmen bleiben Ihre"),
    "privacy_intro": (
        "Paperorg Notes records on this device, then sends audio to Paperorg for transcription and structuring. You can export or delete everything at any time.",
        "Paperorg Notes enregistre sur cet appareil, puis envoie l’audio à Paperorg pour transcription et structuration. Vous pouvez tout exporter ou supprimer à tout moment.",
        "Paperorg Notes nimmt auf diesem Gerät auf und sendet Audio dann an Paperorg zur Transkription und Strukturierung. Sie können alles jederzeit exportieren oder löschen.",
    ),
    "privacy_row_local_title": ("On-device capture", "Enregistrement local", "Lokale Aufnahme"),
    "privacy_row_local_detail": ("Audio is recorded locally first.", "L’audio est d’abord enregistré sur l’appareil.", "Audio wird zuerst lokal aufgenommen."),
    "privacy_row_control_title": ("You stay in control", "Vous restez maître de vos données", "Sie behalten die Kontrolle"),
    "privacy_row_control_detail": ("Export or delete all notes from Settings.", "Exportez ou supprimez toutes les notes dans Réglages.", "Exportieren oder löschen Sie alle Notizen in den Einstellungen."),
    "privacy_row_gdpr_title": ("GDPR", "RGPD", "DSGVO"),
    "privacy_row_gdpr_detail": ("You can download a copy of your data or wipe this device.", "Vous pouvez télécharger une copie de vos données ou effacer cet appareil.", "Sie können eine Kopie Ihrer Daten herunterladen oder dieses Gerät leeren."),
    "privacy_row_providers_title": ("Providers", "Prestataires", "Anbieter"),
    "privacy_row_providers_detail": (
        "Luxembourgish goes to LuxASR first; other languages use OpenAI, then ElevenLabs.",
        "Le luxembourgeois passe d’abord par LuxASR ; les autres langues utilisent OpenAI, puis ElevenLabs.",
        "Luxemburgisch geht zuerst an LuxASR; andere Sprachen nutzen OpenAI, dann ElevenLabs.",
    ),
    "privacy_agree": ("I understand and agree", "J’accepte", "Ich stimme zu"),
    "privacy_view_policy": ("View privacy policy", "Voir la politique de confidentialité", "Datenschutzerklärung anzeigen"),
    "privacy_continue": ("Continue", "Continuer", "Weiter"),
    "record_language": ("Language", "Langue", "Sprache"),
    "record_language_hint": (
        "Pick the language you spoke. Lëtzebuergesch uses LuxASR; other languages use OpenAI.",
        "Choisissez la langue parlée. Le lëtzebuergesch utilise LuxASR ; les autres langues utilisent OpenAI.",
        "Wählen Sie die gesprochene Sprache. Lëtzebuergesch nutzt LuxASR; andere Sprachen nutzen OpenAI.",
    ),
    "record_note_style": ("Note style", "Type de note", "Notizstil"),
    "record_status_idle": ("Tap to record", "Touchez pour enregistrer", "Zum Aufnehmen tippen"),
    "record_status_recording": ("Recording", "Enregistrement", "Aufnahme"),
    "record_status_paused": ("Paused", "En pause", "Pausiert"),
    "record_start": ("Start recording", "Démarrer l’enregistrement", "Aufnahme starten"),
    "record_stop": ("Stop", "Arrêter", "Stopp"),
    "record_pause": ("Pause", "Pause", "Pause"),
    "record_resume": ("Resume", "Reprendre", "Fortsetzen"),
    "record_processing": ("Processing", "Traitement", "Verarbeitung"),
    "record_import": ("Import audio file", "Importer un fichier audio", "Audiodatei importieren"),
    "record_import_hint": ("MP3, WAV or M4A already on this phone", "MP3, WAV ou M4A déjà sur ce téléphone", "MP3, WAV oder M4A bereits auf diesem Telefon"),
    "record_import_hint_limit": (
        "MP3, WAV or M4A · at most %1$d min each",
        "MP3, WAV ou M4A · %1$d min maximum chacun",
        "MP3, WAV oder M4A · höchstens %1$d Min. je Aufnahme",
    ),
    "record_recent": ("Recent notes", "Notes récentes", "Letzte Notizen"),
    "record_recent_subtitle": ("Your last captures", "Vos dernières prises", "Ihre letzten Aufnahmen"),
    "record_empty_title": ("No notes yet", "Aucune note", "Noch keine Notizen"),
    "record_empty_subtitle": ("Tap the orange button to record.", "Touchez le bouton orange pour enregistrer.", "Tippen Sie auf den orangefarbenen Knopf zum Aufnehmen."),
    "record_plan_pro": ("Paperorg Pro", "Paperorg Pro", "Paperorg Pro"),
    "record_plan_free": ("Included minutes", "Minutes incluses", "Inklusive Minuten"),
    "usage_minutes_left": (
        "%1$.1f of %2$d minutes left this month",
        "%1$.1f sur %2$d minutes restantes ce mois-ci",
        "%1$.1f von %2$d Minuten in diesem Monat übrig",
    ),
    "usage_cap": (
        "Each recording can be at most %1$d minutes.",
        "Chaque enregistrement peut durer au plus %1$d minutes.",
        "Eine Aufnahme darf höchstens %1$d Minuten dauern.",
    ),
    "common_dismiss": ("Dismiss", "Ignorer", "Schließen"),
    "common_back": ("Back", "Retour", "Zurück"),
    "common_add": ("Add", "Ajouter", "Hinzufügen"),
    "common_cancel": ("Cancel", "Annuler", "Abbrechen"),
    "common_remove": ("Remove", "Retirer", "Entfernen"),
    "common_delete": ("Delete", "Supprimer", "Löschen"),
    "common_filters": ("Filters", "Filtres", "Filter"),
    "search_title": ("Search", "Recherche", "Suche"),
    "search_placeholder": ("Search transcripts and summaries", "Rechercher dans les transcriptions et résumés", "Transkripte und Zusammenfassungen suchen"),
    "search_empty": ("Type to search titles, transcripts, and summaries.", "Saisissez un mot pour chercher titres, transcriptions et résumés.", "Tippen Sie, um Titel, Transkripte und Zusammenfassungen zu suchen."),
    "search_no_match": ("No matching notes.", "Aucune note correspondante.", "Keine passenden Notizen."),
    "notes_empty_subtitle": ("Record something from the Record tab to build your library.", "Enregistrez depuis l’onglet Enregistrer pour créer votre bibliothèque.", "Nehmen Sie etwas im Tab Aufnahme auf, um Ihre Bibliothek aufzubauen."),
    "notes_no_match_title": ("No matching notes", "Aucune note correspondante", "Keine passenden Notizen"),
    "notes_no_match_subtitle": ("Try clearing a filter or recording something new.", "Effacez un filtre ou enregistrez une nouvelle note.", "Filter löschen oder neu aufnehmen."),
    "notes_favorites": ("Favorites", "Favoris", "Favoriten"),
    "notes_favorites_only": ("Favorites only", "Favoris uniquement", "Nur Favoriten"),
    "notes_all": ("All notes", "Toutes les notes", "Alle Notizen"),
    "notes_all_languages": ("All languages", "Toutes les langues", "Alle Sprachen"),
    "notes_favorite": ("Favorite", "Favori", "Favorit"),
    "status_ready": ("Ready", "Prêt", "Fertig"),
    "status_processing": ("Processing", "Traitement", "Verarbeitung"),
    "status_failed": ("Failed", "Échec", "Fehlgeschlagen"),
    "status_waiting": ("Waiting", "En attente", "Warten"),
    "status_draft": ("Draft", "Brouillon", "Entwurf"),
    "stage_saving": ("Saving audio", "Enregistrement de l’audio", "Audio speichern"),
    "stage_transcribing": ("Transcribing", "Transcription", "Transkription"),
    "stage_checking": ("Checking quality", "Contrôle qualité", "Qualität prüfen"),
    "stage_summarizing": ("Summarizing", "Résumé", "Zusammenfassen"),
    "stage_ready": ("Ready", "Prêt", "Fertig"),
    "output_meeting": ("Meeting notes", "Notes de réunion", "Besprechungsnotizen"),
    "output_brainstorm": ("Brainstorm", "Brainstorming", "Brainstorming"),
    "output_memo": ("Personal memo", "Mémo personnel", "Persönliche Notiz"),
    "output_client_call": ("Client call", "Appel client", "Kundengespräch"),
    "output_interview": ("Interview", "Entretien", "Interview"),
    "output_task_list": ("Task list", "Liste de tâches", "Aufgabenliste"),
    "output_resume": ("Clean resume", "Compte rendu", "Reinschrift"),
    "output_raw": ("Transcript only", "Transcription uniquement", "Nur Transkript"),
    "summary_short": ("Short", "Court", "Kurz"),
    "summary_detailed": ("Detailed", "Détaillé", "Ausführlich"),
    "email_content_summary": ("Summary only", "Résumé uniquement", "Nur Zusammenfassung"),
    "email_content_transcript": ("Full transcript", "Transcription complète", "Vollständiges Transkript"),
    "email_content_both": ("Summary and transcript", "Résumé et transcription", "Zusammenfassung und Transkript"),
    "note_retry_language": ("Language for this audio", "Langue de cet audio", "Sprache für dieses Audio"),
    "note_retry_hint": (
        "Wrong language is the usual reason a transcript looks like junk. Pick what you spoke, then transcribe again.",
        "Une mauvaise langue est la cause habituelle d’une transcription illisible. Choisissez ce que vous avez dit, puis relancez.",
        "Die falsche Sprache ist der übliche Grund für ein unbrauchbares Transkript. Wählen Sie, was Sie gesprochen haben, und transkribieren Sie erneut.",
    ),
    "note_transcribe_again": ("Transcribe again", "Transcrire à nouveau", "Erneut transkribieren"),
    "note_play_audio": ("Play audio", "Écouter l’audio", "Audio abspielen"),
    "note_stop_audio": ("Stop audio", "Arrêter l’audio", "Audio stoppen"),
    "note_resummarize": ("Re-summarize", "Résumer à nouveau", "Erneut zusammenfassen"),
    "note_send_email": ("Send email", "Envoyer un e-mail", "E-Mail senden"),
    "note_export_pdf": ("Export PDF", "Exporter en PDF", "PDF exportieren"),
    "note_tab_transcript": ("Transcript", "Transcription", "Transkript"),
    "note_tab_summary": ("Summary", "Résumé", "Zusammenfassung"),
    "note_tab_actions": ("Actions", "Actions", "Aktionen"),
    "note_no_transcript": ("No transcript yet.", "Pas encore de transcription.", "Noch kein Transkript."),
    "note_no_transcript_hint": (
        "If you already recorded this, tap Transcribe again. Older notes may have stored JSON instead of the spoken words.",
        "Si vous avez déjà enregistré, touchez Transcrire à nouveau. D’anciennes notes peuvent contenir du JSON au lieu des mots.",
        "Wenn Sie das schon aufgenommen haben, tippen Sie auf Erneut transkribieren. Ältere Notizen können JSON statt der gesprochenen Worte speichern.",
    ),
    "note_no_summary": ("No summary yet.", "Pas encore de résumé.", "Noch keine Zusammenfassung."),
    "note_summary_heading": ("Summary", "Résumé", "Zusammenfassung"),
    "note_detail_heading": ("Detail", "Détail", "Detail"),
    "note_no_actions": ("No action items yet.", "Pas encore d’actions.", "Noch keine Aufgaben."),
    "note_key_ideas": ("Key ideas", "Idées clés", "Kernideen"),
    "note_decisions": ("Decisions", "Décisions", "Entscheidungen"),
    "note_open_questions": ("Open questions", "Questions ouvertes", "Offene Fragen"),
    "note_actions": ("Actions", "Actions", "Aktionen"),
    "note_processing_failed": ("Processing failed.", "Le traitement a échoué.", "Verarbeitung fehlgeschlagen."),
    "note_untitled": ("Untitled Recording", "Enregistrement sans titre", "Unbenannte Aufnahme"),
    "settings_title": ("Settings", "Réglages", "Einstellungen"),
    "settings_section_plan": ("Plan", "Offre", "Tarif"),
    "settings_section_language": ("Language", "Langue", "Sprache"),
    "settings_section_vocabulary": ("Vocabulary", "Vocabulaire", "Vokabular"),
    "settings_section_output": ("Output", "Sortie", "Ausgabe"),
    "settings_section_email": ("Email", "E-mail", "E-Mail"),
    "settings_section_privacy": ("Privacy & GDPR", "Confidentialité et RGPD", "Datenschutz & DSGVO"),
    "settings_section_howto": ("How to", "Mode d’emploi", "So geht’s"),
    "settings_section_about": ("About", "À propos", "Info"),
    "settings_section_testing": ("Testing", "Test", "Test"),
    "settings_pro_active": ("Paperorg Pro is active", "Paperorg Pro est actif", "Paperorg Pro ist aktiv"),
    "settings_free_title": ("Included minutes", "Minutes incluses", "Inklusive Minuten"),
    "settings_free_hint": (
        "Free includes 30 minutes of cloud transcription a month. Each recording can be at most 3 minutes. No API keys or sign-in.",
        "L’offre gratuite comprend 30 minutes de transcription cloud par mois. Chaque enregistrement dure au plus 3 minutes. Sans clé API ni inscription.",
        "Free umfasst 30 Minuten Cloud-Transkription pro Monat. Eine Aufnahme darf höchstens 3 Minuten lang sein. Ohne API-Schlüssel und ohne Anmeldung.",
    ),
    "settings_manage_play": ("Manage subscription in Google Play", "Gérer l’abonnement dans Google Play", "Abo in Google Play verwalten"),
    "settings_pro_period": ("Pro, billed per %1$s", "Pro, facturé par %1$s", "Pro, abgerechnet pro %1$s"),
    "settings_pro_price": ("%1$s / %2$s", "%1$s / %2$s", "%1$s / %2$s"),
    "settings_subscribe": ("Subscribe", "S’abonner", "Abonnieren"),
    "settings_plans_missing": (
        "Paperorg Pro is not offered by Google Play on this device yet. It appears once the app is installed from Play with the subscription live.",
        "Google Play ne propose pas encore Paperorg Pro sur cet appareil. L’offre apparaît une fois l’app installée depuis Play avec l’abonnement actif.",
        "Google Play bietet Paperorg Pro auf diesem Gerät noch nicht an. Es erscheint, sobald die App aus Play mit aktivem Abo installiert ist.",
    ),
    "settings_restore": ("Restore purchase", "Restaurer l’achat", "Kauf wiederherstellen"),
    "settings_connected": ("Connected · device %1$s", "Connecté · appareil %1$s", "Verbunden · Gerät %1$s"),
    "settings_not_connected": ("Not connected — connects automatically on first transcription", "Non connecté — connexion automatique à la première transcription", "Nicht verbunden — verbindet sich automatisch bei der ersten Transkription"),
    "settings_default_language": ("Default language", "Langue par défaut", "Standardsprache"),
    "settings_vocab_title": ("Custom vocabulary", "Vocabulaire personnalisé", "Benutzerdefiniertes Vokabular"),
    "settings_vocab_hint": ("Names, brands, and terms to improve transcription accuracy.", "Noms, marques et termes pour améliorer la précision de la transcription.", "Namen, Marken und Begriffe zur Verbesserung der Transkriptionsgenauigkeit."),
    "settings_vocab_free_hint": (
        "Free plan: up to %1$d terms. Pro includes unlimited vocabulary.",
        "Offre gratuite : jusqu’à %1$d termes. Pro inclut un vocabulaire illimité.",
        "Free-Plan: bis zu %1$d Begriffe. Pro enthält unbegrenztes Vokabular.",
    ),
    "settings_vocab_add": ("Add term", "Ajouter un terme", "Begriff hinzufügen"),
    "settings_output_type": ("Default output type", "Type de sortie par défaut", "Standard-Ausgabetyp"),
    "settings_summary_length": ("Summary length", "Longueur du résumé", "Länge der Zusammenfassung"),
    "settings_keep_audio": ("Keep audio files", "Conserver les fichiers audio", "Audiodateien behalten"),
    "settings_delete_after_tx": ("Delete audio after transcription", "Supprimer l’audio après transcription", "Audio nach Transkription löschen"),
    "settings_delete_after_tx_hint": ("Audio is removed as soon as transcription completes.", "L’audio est supprimé dès la fin de la transcription.", "Audio wird gelöscht, sobald die Transkription fertig ist."),
    "settings_delete_after": ("Delete audio after", "Supprimer l’audio après", "Audio löschen nach"),
    "settings_audio_off_hint": ("Audio is removed after transcription. Retention options are unavailable.", "L’audio est supprimé après transcription. Les durées de conservation ne s’appliquent pas.", "Audio wird nach der Transkription entfernt. Aufbewahrungsoptionen entfallen."),
    "retention_never": ("Never", "Jamais", "Nie"),
    "retention_7": ("7 days", "7 jours", "7 Tage"),
    "retention_30": ("30 days", "30 jours", "30 Tage"),
    "retention_90": ("90 days", "90 jours", "90 Tage"),
    "settings_export_all": ("Export all data", "Exporter toutes les données", "Alle Daten exportieren"),
    "settings_delete_all": ("Delete all data", "Supprimer toutes les données", "Alle Daten löschen"),
    "settings_delete_all_title": ("Delete all data?", "Supprimer toutes les données ?", "Alle Daten löschen?"),
    "settings_delete_all_body": (
        "This permanently deletes all notes, audio, transcripts, and local settings on this device.",
        "Cette action supprime définitivement toutes les notes, tous les enregistrements audio, toutes les transcriptions et tous les réglages locaux.",
        "Damit werden alle Notizen, Audioaufnahmen, Transkripte und lokalen Einstellungen unwiderruflich gelöscht.",
    ),
    "settings_delete_everything": ("Delete everything", "Tout supprimer", "Alles löschen"),
    "howto_record": (
        "Tap the orange button, speak, then tap Stop. Paperorg transcribes and can email the note by itself.",
        "Touchez le bouton orange, parlez, puis Stop. Paperorg transcrit et peut envoyer la note par e-mail tout seul.",
        "Tippen Sie auf den orangefarbenen Knopf, sprechen Sie, dann auf Stopp. Paperorg transkribiert und kann die Notiz selbst per E-Mail senden.",
    ),
    "howto_import": (
        "Or import an MP3, WAV or M4A already on this phone. It becomes a note the same way a recording does.",
        "Ou importez un MP3, WAV ou M4A déjà sur ce téléphone. Il devient une note comme un enregistrement.",
        "Oder importieren Sie eine MP3-, WAV- oder M4A-Datei, die schon auf diesem Telefon liegt. Sie wird wie eine Aufnahme zu einer Notiz.",
    ),
    "howto_free": (
        "Free is 30 minutes a month, in recordings of at most 3 minutes — a voice memo, not a meeting.",
        "L’offre gratuite, c’est 30 minutes par mois, en enregistrements de 3 minutes maximum — un mémo vocal, pas une réunion.",
        "Free sind 30 Minuten im Monat, in Aufnahmen von höchstens 3 Minuten — eine Sprachnotiz, kein Meeting.",
    ),
    "howto_pro": (
        "Pro is 10 hours a month and up to 3 hours in one recording, for meetings.",
        "Pro, c’est 10 heures par mois et jusqu’à 3 heures en un enregistrement, pour les réunions.",
        "Pro sind 10 Stunden im Monat und bis zu 3 Stunden in einer Aufnahme, für Meetings.",
    ),
    "about_version": ("Version", "Version", "Version"),
    "about_providers": ("Transcription providers", "Fournisseurs de transcription", "Transkriptionsanbieter"),
    "about_lux_path": ("Luxembourgish: LuxASR (primary) → ElevenLabs → OpenAI", "Luxembourgeois : LuxASR (principal) → ElevenLabs → OpenAI", "Luxemburgisch: LuxASR (primär) → ElevenLabs → OpenAI"),
    "about_other_path": ("Other languages: OpenAI (primary) → ElevenLabs", "Autres langues : OpenAI (principal) → ElevenLabs", "Andere Sprachen: OpenAI (primär) → ElevenLabs"),
    "about_luxasr_title": ("Lëtzebuergesch transcription", "Transcription en luxembourgeois", "Lëtzebuergesch-Transkription"),
    "about_luxasr_credit": ("Powered by LuxASR, developed at the University of Luxembourg.", "Propulsé par LuxASR, développé à l’Université du Luxembourg.", "Ermöglicht durch LuxASR, entwickelt an der Universität Luxemburg."),
    "settings_luxasr_toggle": ("Use LuxASR for Lëtzebuergesch", "Utiliser LuxASR pour le luxembourgeois", "LuxASR für Lëtzebuergesch verwenden"),
    "settings_luxasr_hint": (
        "Off sends Lëtzebuergesch to ElevenLabs instead, so the two can be compared on the same recording.",
        "Désactivé, le luxembourgeois est envoyé à ElevenLabs, ce qui permet de comparer les deux sur le même enregistrement.",
        "Aus schickt Lëtzebuergesch stattdessen an ElevenLabs, damit sich beide an derselben Aufnahme vergleichen lassen.",
    ),
    "email_send_after": ("Send email after transcription", "Envoyer un e-mail après la transcription", "E-Mail nach der Transkription senden"),
    "email_send_after_hint": (
        "Paperorg can send your note automatically when transcription finishes. Add who should receive it below.",
        "Paperorg peut envoyer votre note automatiquement à la fin de la transcription. Ajoutez les destinataires ci-dessous.",
        "Paperorg kann Ihre Notiz automatisch senden, wenn die Transkription fertig ist. Fügen Sie unten Empfänger hinzu.",
    ),
    "email_checking": ("Checking server email…", "Vérification de l’e-mail du serveur…", "Server-E-Mail wird geprüft…"),
    "email_sends_as": ("Sends as %1$s", "Envoi en tant que %1$s", "Sendet als %1$s"),
    "email_server_fallback": ("Paperorg sends from the server. Add who should receive it below.", "Paperorg envoie depuis le serveur. Ajoutez les destinataires ci-dessous.", "Paperorg sendet vom Server. Fügen Sie unten Empfänger hinzu."),
    "email_add_address": ("Add email address", "Ajouter une adresse e-mail", "E-Mail-Adresse hinzufügen"),
    "email_content": ("Content", "Contenu", "Inhalt"),
    "email_attach_audio": ("Attach audio", "Joindre l’audio", "Audio anhängen"),
    "email_attach_pdf": ("Attach PDF", "Joindre le PDF", "PDF anhängen"),
    "email_attach_markdown": ("Attach Markdown", "Joindre le Markdown", "Markdown anhängen"),
    "email_review": ("Review before send", "Vérifier avant envoi", "Vor dem Senden prüfen"),
    "email_review_hint": (
        "Only applies when you tap Send email on a note. Automatic post-recording email always sends without review.",
        "S’applique seulement quand vous touchez Envoyer un e-mail sur une note. L’envoi automatique part sans relecture.",
        "Gilt nur, wenn Sie auf einer Notiz E-Mail senden tippen. Die automatische E-Mail nach der Aufnahme geht ohne Prüfung raus.",
    ),
    "email_test_address": ("Test address", "Adresse de test", "Testadresse"),
    "email_send_test": ("Send test", "Envoyer un test", "Test senden"),
    "email_sending": ("Sending…", "Envoi…", "Senden…"),
    "billing_restored": ("Paperorg Pro restored.", "Paperorg Pro restauré.", "Paperorg Pro wiederhergestellt."),
    "billing_none": ("No Paperorg Pro subscription on this Google account.", "Aucun abonnement Paperorg Pro sur ce compte Google.", "Kein Paperorg-Pro-Abo auf diesem Google-Konto."),
    "error_mic": ("Could not start the microphone.", "Impossible de démarrer le microphone.", "Mikrofon konnte nicht gestartet werden."),
    "error_play": ("Could not play the recording.", "Impossible de lire l’enregistrement.", "Aufnahme konnte nicht abgespielt werden."),
    "error_pdf": ("Could not create the PDF.", "Impossible de créer le PDF.", "PDF konnte nicht erstellt werden."),
    "error_no_recipients": ("Add at least one recipient in Settings.", "Ajoutez au moins un destinataire dans Réglages.", "Fügen Sie in den Einstellungen mindestens einen Empfänger hinzu."),
    "error_empty_note": ("This note has nothing to send yet.", "Cette note n’a encore rien à envoyer.", "Diese Notiz hat noch nichts zu senden."),
    "email_sent": ("Email sent.", "E-mail envoyé.", "E-Mail gesendet."),
    "email_test_sent": ("Test email sent to %1$s", "E-mail de test envoyé à %1$s", "Test-E-Mail gesendet an %1$s"),
    "chooser_export": ("Export notes", "Exporter les notes", "Notizen exportieren"),
    "chooser_pdf": ("Export PDF", "Exporter en PDF", "PDF exportieren"),
    "notification_recording": ("Recording", "Enregistrement", "Aufnahme"),
    "notification_recording_channel": ("Shown while Paperorg Notes is recording", "Affichée pendant l’enregistrement", "Wird während der Aufnahme angezeigt"),
    "notification_stop": ("Stop", "Arrêter", "Stopp"),
    "notification_recording_text": ("Recording · %1$s", "Enregistrement · %1$s", "Aufnahme · %1$s"),
}


def xml_text(value: str) -> str:
    escaped = escape(value, {"'": r"\'", '"': r"\""})
    return escaped


def write_locale(folder: str, index: int) -> None:
    dest = ROOT / folder
    dest.mkdir(parents=True, exist_ok=True)
    lines = ['<?xml version="1.0" encoding="utf-8"?>', "<resources>"]
    for key, triple in CATALOG.items():
        lines.append(f'    <string name="{key}">{xml_text(triple[index])}</string>')
    lines.append("</resources>\n")
    (dest / "strings.xml").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    write_locale("values", 0)
    write_locale("values-fr", 1)
    write_locale("values-de", 2)
    print(f"wrote {len(CATALOG)} keys")


if __name__ == "__main__":
    main()
