import UIKit

struct ExportBranding {
    let brandName: String
    let brandSubtitle: String
    let logo: UIImage?
    let footerText: String

    @MainActor
    static func from(settings: SettingsService, storage: StorageService) -> ExportBranding? {
        guard settings.usesProBackend else { return nil }
        let name = settings.exportBrandName.trimmingCharacters(in: .whitespacesAndNewlines)
        let subtitle = settings.exportBrandSubtitle.trimmingCharacters(in: .whitespacesAndNewlines)
        let logo = storage.loadCustomExportLogo() ?? UIImage(named: "LaunchLogo")
        return ExportBranding(
            brandName: name.isEmpty ? "Paperorg Notes" : name,
            brandSubtitle: subtitle,
            logo: logo,
            footerText: "Generated by \(name.isEmpty ? "Paperorg Notes" : name)"
        )
    }
}
